let canvas,ctx,treeData={persons:[],relationships:[]},selectedPerson=null,offsetX=0,offsetY=0,isDragging=false,scale=1,editingPerson=null;
const NODE_WIDTH=140,NODE_HEIGHT=64,STORAGE_KEY='family_tree_data';
document.addEventListener('DOMContentLoaded',()=>{initCanvas();loadFromStorage();setupEvents();updateStats();});
function initCanvas(){canvas=document.getElementById('tree-canvas');ctx=canvas.getContext('2d');resizeCanvas();window.addEventListener('resize',()=>{resizeCanvas();renderTree();});}
function resizeCanvas(){const c=canvas.parentElement;canvas.width=c.clientWidth;canvas.height=c.clientHeight;}
function setupEvents(){canvas.addEventListener('mousedown',(e)=>{isDragging=true;dragStartX=e.clientX-offsetX;dragStartY=e.clientY-offsetY;canvas.style.cursor='grabbing';});
canvas.addEventListener('mousemove',(e)=>{if(!isDragging)return;offsetX=e.clientX-dragStartX;offsetY=e.clientY-dragStartY;});
canvas.addEventListener('mouseup',()=>{isDragging=false;canvas.style.cursor='grab';});
canvas.addEventListener('wheel',(e)=>{e.preventDefault();scale=Math.max(0.2,Math.min(3,scale+(e.deltaY>0?-0.05:0.05)));},{passive:false});
canvas.addEventListener('click',(e)=>{if(isDragging)return;const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left-offsetX)/scale;const y=(e.clientY-rect.top-offsetY)/scale;const clicked=treeData.persons.find(p=>x>=p.position_x-NODE_WIDTH/2&&x<=p.position_x+NODE_WIDTH/2&&y>=p.position_y-NODE_HEIGHT/2&&y<=p.position_y+NODE_HEIGHT/2);if(clicked)showPerson(clicked);else hideSidebar();});
document.getElementById('zoom-in').onclick=()=>{scale=Math.min(3,scale+0.1);};
document.getElementById('zoom-out').onclick=()=>{scale=Math.max(0.2,scale-0.1);};
document.getElementById('fit-view').onclick=()=>{if(!treeData.persons.length){scale=1;offsetX=canvas.width/2;offsetY=canvas.height/2;return;}let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;treeData.persons.forEach(p=>{minX=Math.min(minX,p.position_x);minY=Math.min(minY,p.position_y);maxX=Math.max(maxX,p.position_x);maxY=Math.max(maxY,p.position_y);});const pad=100,scaleX=(canvas.width/scale)/(maxX-minX+NODE_WIDTH+pad),scaleY=(canvas.height/scale)/(maxY-minY+NODE_HEIGHT+pad);scale=Math.min(scaleX,scaleY,1.5);const cx=(minX+maxX)/2,cy=(minY+maxY)/2;offsetX=canvas.width/2-cx*scale;offsetY=canvas.height/2-cy*scale;};
document.getElementById('add-person-btn').onclick=()=>showModal();
document.getElementById('export-json').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(treeData,null,2)],{type:'application/json'}));a.download=`family-tree-${new Date().toISOString().slice(0,19)}.json`;a.click();showNotification('Экспорт выполнен','success');};
document.getElementById('import-btn').onclick=()=>document.getElementById('file-input').click();
document.getElementById('file-input').onchange=(e)=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=(ev)=>{try{const d=JSON.parse(ev.target.result);if(d.persons&&d.relationships){treeData=d;saveToStorage();updateSelects();renderTree();updateStats();fitView();showNotification('Импорт выполнен','success');}else showNotification('Неверный формат','error');}catch(err){showNotification('Ошибка файла','error');}};r.readAsText(f);e.target.value='';};
document.getElementById('clear-data').onclick=()=>{if(confirm('Очистить всё дерево?')){treeData={persons:[],relationships:[]};saveToStorage();selectedPerson=null;hideSidebar();renderTree();updateStats();showNotification('Очищено','success');}};
document.getElementById('load-example').onclick=()=>{loadExample();};
document.getElementById('close-sidebar').onclick=hideSidebar;
document.getElementById('modal-close').onclick=hideModal;
document.getElementById('edit-person-btn').onclick=()=>{if(selectedPerson)showModal(selectedPerson);};
document.getElementById('delete-person-btn').onclick=()=>{if(selectedPerson&&confirm('Удалить?'))deletePerson(selectedPerson.id);};
document.getElementById('person-form').onsubmit=(e)=>{e.preventDefault();const data={name:document.getElementById('person-name').value.trim(),gender:document.getElementById('person-gender').value,birth_date:document.getElementById('person-birth').value,death_date:document.getElementById('person-death').value,birth_place:document.getElementById('person-birth-place').value,death_place:document.getElementById('person-death-place').value,occupation:document.getElementById('person-occupation').value,bio:document.getElementById('person-bio').value};if(!data.name){showNotification('Укажите имя','error');return;}const fid=document.getElementById('person-father').value,mid=document.getElementById('person-mother').value,sid=document.getElementById('person-spouse').value;if(editingPerson){const idx=treeData.persons.findIndex(p=>p.id===editingPerson.id);if(idx!==-1)treeData.persons[idx]={...treeData.persons[idx],...data};showNotification('Обновлено','success');}else{const np={id:Date.now().toString(36)+Math.random().toString(36).substr(2,6),...data,position_x:500+Math.random()*200,position_y:300+Math.random()*200};treeData.persons.push(np);if(fid)treeData.relationships.push({id:Date.now().toString(36)+Math.random().toString(36),person1_id:fid,person2_id:np.id,relationship_type:'parent-child'});if(mid)treeData.relationships.push({id:Date.now().toString(36)+Math.random().toString(36),person1_id:mid,person2_id:np.id,relationship_type:'parent-child'});if(sid)treeData.relationships.push({id:Date.now().toString(36)+Math.random().toString(36),person1_id:sid,person2_id:np.id,relationship_type:'spouse'});showNotification('Добавлено','success');}saveToStorage();updateSelects();renderTree();updateStats();hideModal();editingPerson=null;};}
function saveToStorage(){localStorage.setItem(STORAGE_KEY,JSON.stringify(treeData));}
function loadFromStorage(){const s=localStorage.getItem(STORAGE_KEY);if(s){try{const d=JSON.parse(s);treeData={persons:d.persons||[],relationships:d.relationships||[]};}catch(e){loadExample();}}else loadExample();updateSelects();renderTree();}
function loadExample(){treeData={persons:[{id:'p1',name:'Иван Петров',gender:'male',birth_date:'1950-05-15',birth_place:'Москва',occupation:'Инженер',position_x:500,position_y:80},{id:'p2',name:'Мария Петрова',gender:'female',birth_date:'1952-08-20',birth_place:'Москва',occupation:'Учитель',position_x:500,position_y:80},{id:'p3',name:'Алексей Петров',gender:'male',birth_date:'1975-03-10',birth_place:'Москва',occupation:'Врач',position_x:350,position_y:220},{id:'p4',name:'Елена Петрова',gender:'female',birth_date:'1978-07-25',birth_place:'СПб',occupation:'Архитектор',position_x:650,position_y:220},{id:'p5',name:'Дмитрий Петров',gender:'male',birth_date:'2000-01-01',birth_place:'Москва',occupation:'Студент',position_x:350,position_y:380},{id:'p6',name:'Анна Петрова',gender:'female',birth_date:'2002-06-15',birth_place:'Москва',occupation:'Студентка',position_x:650,position_y:380}],relationships:[{id:'r1',person1_id:'p1',person2_id:'p2',relationship_type:'spouse'},{id:'r2',person1_id:'p1',person2_id:'p3',relationship_type:'parent-child'},{id:'r3',person1_id:'p2',person2_id:'p3',relationship_type:'parent-child'},{id:'r4',person1_id:'p3',person2_id:'p4',relationship_type:'spouse'},{id:'r5',person1_id:'p3',person2_id:'p5',relationship_type:'parent-child'},{id:'r6',person1_id:'p4',person2_id:'p5',relationship_type:'parent-child'},{id:'r7',person1_id:'p3',person2_id:'p6',relationship_type:'parent-child'},{id:'r8',person1_id:'p4',person2_id:'p6',relationship_type:'parent-child'}]};saveToStorage();updateSelects();renderTree();updateStats();fitView();showNotification('Пример загружен','success');}
function renderTree(){if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(offsetX,offsetY);ctx.scale(scale,scale);treeData.relationships.forEach(r=>{const p1=treeData.persons.find(p=>p.id===r.person1_id),p2=treeData.persons.find(p=>p.id===r.person2_id);if(!p1||!p2)return;if(r.relationship_type==='spouse'){ctx.beginPath();ctx.moveTo(p1.position_x,p1.position_y);ctx.lineTo(p2.position_x,p2.position_y);ctx.strokeStyle='#ff9800';ctx.lineWidth=2.5;ctx.setLineDash([8,6]);ctx.stroke();ctx.setLineDash([]);}else if(r.relationship_type==='parent-child'){ctx.beginPath();ctx.moveTo(p1.position_x,p1.position_y+NODE_HEIGHT/2);ctx.bezierCurveTo(p1.position_x,p1.position_y+(p2.position_y-p1.position_y)*0.3,p2.position_x,p2.position_y-(p2.position_y-p1.position_y)*0.3,p2.position_x,p2.position_y-NODE_HEIGHT/2);ctx.strokeStyle='#8bc34a';ctx.lineWidth=2;ctx.stroke();}});treeData.persons.forEach(p=>{const x=p.position_x||400,y=p.position_y||300,isSel=selectedPerson&&selectedPerson.id===p.id,isAlive=!p.death_date;ctx.fillStyle=p.gender==='male'?'#e3f2fd':'#fce4ec';if(!isAlive)ctx.fillStyle='#e0e0e0';if(isSel)ctx.fillStyle='#fff9c4';ctx.beginPath();ctx.roundRect(x-NODE_WIDTH/2,y-NODE_HEIGHT/2,NODE_WIDTH,NODE_HEIGHT,10);ctx.fill();ctx.strokeStyle=isAlive?'#4CAF50':'#999';ctx.lineWidth=isSel?3:2;ctx.beginPath();ctx.roundRect(x-NODE_WIDTH/2,y-NODE_HEIGHT/2,NODE_WIDTH,NODE_HEIGHT,10);ctx.stroke();ctx.fillStyle='#333';ctx.font='bold 12px -apple-system';ctx.textAlign='center';let dn=p.name;if(dn.length>18)dn=dn.substring(0,16)+'...';ctx.fillText(dn,x,y-8);if(p.birth_date||p.death_date){ctx.font='10px -apple-system';ctx.fillStyle='#888';let d='';if(p.birth_date)d+=p.birth_date.split('-')[0];if(p.death_date&&p.death_date!=='')d+=' - '+p.death_date.split('-')[0];ctx.fillText(d||'?',x,y+12);}ctx.font='16px -apple-system';ctx.fillStyle=p.gender==='male'?'#2196F3':'#E91E63';ctx.fillText(p.gender==='male'?'♂':'♀',x-NODE_WIDTH/2+16,y-NODE_HEIGHT/2+22);});ctx.restore();document.getElementById('zoom-percent').innerText=Math.round(scale*100);}
function showPerson(p){selectedPerson=p;document.getElementById('detail-name').innerText=p.name;document.getElementById('detail-gender').innerText=p.gender==='male'?'Мужской':'Женский';document.getElementById('detail-birth').innerText=p.birth_date?p.birth_date.split('-').reverse().join('.'):'—';document.getElementById('detail-death').innerText=p.death_date?p.death_date.split('-').reverse().join('.'):'—';document.getElementById('detail-birth-place').innerText=p.birth_place||'—';document.getElementById('detail-death-place').innerText=p.death_place||'—';document.getElementById('detail-occupation').innerText=p.occupation||'—';document.getElementById('detail-bio').innerText=p.bio||'Нет данных';let d=[];if(p.birth_date)d.push(p.birth_date.split('-').reverse().join('.'));if(p.death_date&&p.death_date!=='')d.push(p.death_date.split('-').reverse().join('.'));document.getElementById('detail-dates').innerText=d.join(' — ');document.getElementById('sidebar').classList.remove('hidden');}
function hideSidebar(){document.getElementById('sidebar').classList.add('hidden');selectedPerson=null;}
function showModal(p=null){editingPerson=p;const m=document.getElementById('modal');if(p){document.getElementById('modal-title').innerText='Редактировать персону';document.getElementById('person-name').value=p.name||'';document.getElementById('person-gender').value=p.gender||'male';document.getElementById('person-birth').value=p.birth_date||'';document.getElementById('person-death').value=p.death_date||'';document.getElementById('person-birth-place').value=p.birth_place||'';document.getElementById('person-death-place').value=p.death_place||'';document.getElementById('person-occupation').value=p.occupation||'';document.getElementById('person-bio').value=p.bio||'';}else{document.getElementById('modal-title').innerText='Добавить персону';document.getElementById('person-form').reset();}updateSelects();m.classList.add('show');}
function hideModal(){document.getElementById('modal').classList.remove('show');editingPerson=null;}
function deletePerson(id){treeData.persons=treeData.persons.filter(p=>p.id!==id);treeData.relationships=treeData.relationships.filter(r=>r.person1_id!==id&&r.person2_id!==id);saveToStorage();updateSelects();if(selectedPerson&&selectedPerson.id===id)hideSidebar();renderTree();updateStats();showNotification('Удалено','success');}
function updateSelects(){const f=document.getElementById('person-father'),m=document.getElementById('person-mother'),s=document.getElementById('person-spouse');if(!f)return;f.innerHTML='<option value="">— Отец —</option>'+treeData.persons.filter(p=>p.gender==='male').map(p=>`<option value="${p.id}">${p.name}</option>`).join('');m.innerHTML='<option value="">— Мать —</option>'+treeData.persons.filter(p=>p.gender==='female').map(p=>`<option value="${p.id}">${p.name}</option>`).join('');s.innerHTML='<option value="">— Не указан(а) —</option>'+treeData.persons.filter(p=>!editingPerson||p.id!==editingPerson.id).map(p=>`<option value="${p.id}">${p.name}</option>`).join('');if(editingPerson){const childRels=treeData.relationships.filter(r=>r.relationship_type==='parent-child'&&r.person2_id===editingPerson.id);const fatherRel=childRels.find(r=>{const pa=treeData.persons.find(p=>p.id===r.person1_id);return pa&&pa.gender==='male';});const motherRel=childRels.find(r=>{const pa=treeData.persons.find(p=>p.id===r.person1_id);return pa&&pa.gender==='female';});const spouseRel=treeData.relationships.find(r=>r.relationship_type==='spouse'&&(r.person1_id===editingPerson.id||r.person2_id===editingPerson.id));if(fatherRel)f.value=fatherRel.person1_id;if(motherRel)m.value=motherRel.person1_id;if(spouseRel){const sid=spouseRel.person1_id===editingPerson.id?spouseRel.person2_id:spouseRel.person1_id;s.value=sid;}}}
function updateStats(){document.getElementById('persons-count').innerText=treeData.persons.length;}
function showNotification(msg,type){const c=document.getElementById('notification-container');const n=document.createElement('div');n.className=`notification ${type}`;const icons={success:'✅',error:'❌',warning:'⚠️',info:'ℹ️'};n.innerHTML=`${icons[type]||'ℹ️'} ${msg}`;c.appendChild(n);setTimeout(()=>{n.style.opacity='0';setTimeout(()=>n.remove(),300);},3000);}
function fitView(){if(!treeData.persons.length){scale=1;offsetX=canvas.width/2;offsetY=canvas.height/2;return;}let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;treeData.persons.forEach(p=>{minX=Math.min(minX,p.position_x);minY=Math.min(minY,p.position_y);maxX=Math.max(maxX,p.position_x);maxY=Math.max(maxY,p.position_y);});const pad=100,viewW=canvas.width/scale,viewH=canvas.height/scale,cw=maxX-minX+NODE_WIDTH+pad,ch=maxY-minY+NODE_HEIGHT+pad;const sx=viewW/cw,sy=viewH/ch;scale=Math.min(sx,sy,1.5);const cx=(minX+maxX)/2,cy=(minY+maxY)/2;offsetX=canvas.width/2-cx*scale;offsetY=canvas.height/2-cy*scale;}
CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){if(w<2*r)r=w/2;if(h<2*r)r=h/2;this.moveTo(x+r,y);this.lineTo(x+w-r,y);this.quadraticCurveTo(x+w,y,x+w,y+r);this.lineTo(x+w,y+h-r);this.quadraticCurveTo(x+w,y+h,x+w-r,y+h);this.lineTo(x+r,y+h);this.quadraticCurveTo(x,y+h,x,y+h-r);this.lineTo(x,y+r);this.quadraticCurveTo(x,y,x+r,y);return this;};